version: 2
jobs:
  build:
    working_directory: ~/test_folder
    docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: test encrypt variables
          command: echo ${AZURE_USER_NAME}
      - run:
          name: set script excecutable
          command: sudo chmod +x ./install_powershell_core ./CustomTasks/slack_integration/slack_messanger
      - run:
          name: install powershell core
          command: ./install_powershell_core
      - run:
          name: Log in to azure
          command: az login --service-principal -u "43cd38ac-48f7-434d-9834-ef3fadf4a0d3" -p "vRt/ifcsjnf8wgVNLtOT+q6hQG6gWkV8dHaaUZpHEEA="  --tenant  "9c35f838-72ed-4b90-a411-bb1f92c031b8"
      - run:
          name: Deploy linux VM
          command: az group deployment create --name ExampleDeployment --resource-group ${RESOURCE_GROUP} --template-file "${TEMPLATE_FILE_PATH}" --parameters "${PARAMETERS_FILE_PATH}"
      - run:
          name: end build notification
          command: ./CustomTasks/slack_integration/slack_messanger ${SLACK_WEBHOOK_URI} dsd efesf efesfe "New vm was deployed." desktop_computer


