version: 2
jobs:
  build:
    working_directory: ~/test_folder
    docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: run npm install 
          command: node -v 
      - run:
          name: run npm install 
          command: sudo npm cache clean -f
      - run:
          name: run npm install 
          command: sudo npm install -g n
      - run:
          name: run npm install 
          command:  sudo n stable
      - run:
          name: run npm install 
          command: node -v
      - run:
          name: test encrypt variables
          command: echo ${AZURE_USER_NAME}
      - run:
          name: set script excecutable
          command: sudo chmod +x ./install_powershell_core ./CustomTasks/slack_integration/slack_messanger
      - run:
          name: install powershell core
          command: ./install_powershell_core
      - run:
          name: Login to azure
          command: az login --service-principal -u ${LOGIN_APP_ID} -p ${LOGIN_KEY} --tenant ${LOGIN_TENANT}
 #     - run:
 #         name: Deploy linux VM
 #         command: az group deployment create --name ExampleDeployment --resource-group ${RESOURCE_GROUP} --template-file "${TEMPLATE_FILE_PATH}" --parameters "${PARAMETERS_FILE_PATH}"
      - run:
          name: deploy grid's
          command: node ./CustomTasks/Deployer/deploymentManager.js ${RESOURCE_GROUP} GRID_DEPLOY 3 0 0 0  ./Templates/Grid/template.json ./Templates/Grid/parametersWithTokens.json   ./Templates/Grid/parameters.json  parameterValuePath  eastus
 #     - run:
 #         name: deploy nod's
 #         command: 
      - run:
          name: send build notification
          command: ./CustomTasks/slack_integration/slack_messanger ${SLACK_WEBHOOK_URI} dsd efesf efesfe "New vm was deployed." desktop_computer
      - run:
          name: Logout from azure
          command: az logout
