version: 2
jobs:
  build:
    working_directory: ~/test_folder
    docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: run npm install 
          command: sudo npm cache clean -f
      - run:
          name: generate ssh key 
          command: sudo ssh-keygen -b 2048 -t rsa -f ./sshkey -q -N ""
      - run:
          name: check if exist ssh key
          command: sudo ls -la
      - store_artifacts:
          path: ./sshkey.pub
          destination: artifacts
    #   - run:
    #       name: run npm install 
    #       command: sudo npm install -g n
    #   - run:
    #       name: run npm install 
    #       command: sudo npm install -g n
    #   - run:
    #       name: run npm install 
    #       command:  sudo n stable
    #   - run:
    #       name: set script excecutable
    #       command: sudo chmod +x ./install_powershell_core ./CustomTasks/slack_integration/slack_messanger
    #   - run:
    #       name: install azure cli
    #       command: ./install_powershell_core
    #   - run:
    #       name: Login to azure
    #       command: az login --service-principal -u ${LOGIN_APP_ID} -p ${LOGIN_KEY} --tenant ${LOGIN_TENANT}
    #   - run:
    #       name: Create resource group
    #       command: node ./CustomTasks/Deployer/deploymentManager.js ${RESOURCE_GROUP} ACTION_CREATE_RESOURCE_GROUP 3 ${FIREFOX_NODS} ${CHROME_NODS} ${EDGE_NODS} ${IE11_NODS} ${AZURE_REGION}  ${CONTROLLER_BLOBS_CONTAINER_CS}
    #   - run:
    #       name: Deploy nods
    #       command: node ./CustomTasks/Deployer/deploymentManager.js ${RESOURCE_GROUP} NODS_DEPLOY 3 ${FIREFOX_NODS} ${CHROME_NODS} ${EDGE_NODS} ${IE11_NODS} ${AZURE_REGION}  ${CONTROLLER_BLOBS_CONTAINER_CS}
    #   - run:
    #       name: Deploy grids
    #       command: node ./CustomTasks/Deployer/deploymentManager.js ${RESOURCE_GROUP} GRID_DEPLOY 3 ${FIREFOX_NODS} ${CHROME_NODS} ${EDGE_NODS} ${IE11_NODS} ${AZURE_REGION}  ${CONTROLLER_BLOBS_CONTAINER_CS}
    #   - run:
    #       name: send build notification
    #       command: ./CustomTasks/slack_integration/slack_messanger ${SLACK_WEBHOOK_URI} dsd efesf efesfe "New vm was deployed." desktop_computer
    #   - run:
    #       name: Logout from azure
    #       command: az logout


